[versions]
kotlin = "2.1.10"
agp = "8.7.3"
android-minSdk = "24"
android-compileSdk = "34"
konanplugin = "1.0.0"
io = "0.6.0"

[libraries]
io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "io" }

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
konanplugin = { id = "io.github.lemcoder.konanplugin", version.ref = "konanplugin" }


